### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by bhavin-concetto** [inbrainai/sdk-android-example-project#14]
- Unable to fetch latest version of inBrain from jitpack.io due to Could not GET 'https://jitpack.io/com/github/inbrainai/sdk-android/1.0.20/sdk-android-1.0.20.pom'. Received status code 401 from server: Unauthorized

**Comment by Tiny-Angel305** [comment]
@bhavin-concetto , try to go to https://jitpack.io/private#auth and get your authToken for jitpack.io access.
